using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using System.Runtime.InteropServices;
using Newtonsoft.Json;
using Puma.MDE.Common.Utilities;

namespace Puma.MDE.Data
{
    [ComVisible(true)]
    [Serializable]
    public class SwapOrder : INotifyPropertyChanged
    {


        public SwapOrder() { }
        public SwapOrder(int id) { Id = id; }
        public SwapOrder(SwapAccount account)
        {
            this.Account = account;
            this.OrderType = TypeManastOrder.None;
            this.TradeDate = DateTime.Today;

        }
        public int Id { get; protected set; }
        public String DbName { get; set; }
        public int AccountId { get; set; }
        public const string CommentAutomatic = "Automatic";
        public bool IsAutoGenerated { get { return Description.StartsWith(CommentAutomatic); } } // modified by DD 30/6/2010

        [JsonIgnore]
        public SwapAccount Account
        {
            get
            {
                return null;
            }
            set
            {
                this.AccountId = value.Id;
                NotifyChange();
            }
        }
        public String Description { get; set; }
        public int Type { get; set; }
        public string xType { get { return ((TypeManastOrder)this.Type).ToString(); } }
        public decimal IndexValue { get; set; }
        public DateTime m_tradeDate;
        public DateTime TradeDate
        {
            get => m_tradeDate;
            set
            {
                m_tradeDate = value;
                ValueDate = WorkingDays.AddWorkingDays(m_tradeDate, 2);
                OnPropertyChanged(nameof(ValueDate));
                NotifyChange();
            }
        }
        public DateTime ValueDate { get; set; }
        public DateTime? DateExecuted { get; set; }
        public bool IsDateExecutedNull()
        {
            return !DateExecuted.HasValue;
        }
        public void SetDateExecutedNull()
        {
            DateExecuted = null;
        }

        /// <summary>
        /// Gets or sets the DateExecuted value with null value handling.
        /// Avoids the occurrence of exceptions when the DateExecuted field value is called from the grid.
        /// </summary>
        /// <value>The date executed or null.</value>
        public Object DateExecutedOrNull
        {
            get
            {
                return (IsDateExecutedNull()) ? null : (object)DateExecuted;
            }
            set
            {
                if (value != null)
                    DateExecuted = (DateTime)value;
                else
                    SetDateExecutedNull();
                OnPropertyChanged(nameof(DateExecutedOrNull));
            }
        }
        public int RowVersion { get; set; }
        public double? Certificates { get; set; }
        public bool IsCertificatesNull()
        {
            return !Certificates.HasValue;
        }

        public SwapUser User { get; set; }
        public int UpdatePoolUpon { get; set; }
        public TypeManastOrder OrderType { get { return (TypeManastOrder)this.Type; } set { this.Type = (byte)value; NotifyChange(); } }
        public double CertificatesOrZero { get { return (!Certificates.HasValue) ? (0.0) : (Certificates.Value); } }

        public bool IsUserIDNull()
        {
            return User == null;
        }
        public string UserLoginOrNull
        {
            get
            {
                return (IsUserIDNull()) ? null : User.Login;
            }
        }

        public IEnumerable<SwapTrade> TradeRows => null;
        public int TradeRowsCount => 1;


        public void AddNewTrade()
        {
            SwapTrade trade = new SwapTrade(this);
            NotifyChange();
        }

        public double Net()
        {
            double sum = 0.0;
            foreach (SwapTrade rotr in TradeRows)
                sum += rotr.Net;
            NotifyChange();
            return sum;
        }

        public void NotifyChange()
        {
            var properties = GetType().GetProperties(BindingFlags.Instance | BindingFlags.Public);
            foreach (var prop in properties)
            {
                OnPropertyChanged(prop.Name);
            }
        }

        public event PropertyChangedEventHandler PropertyChanged;
        protected void OnPropertyChanged(string name) => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));
    }
}
